---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spring-artemis-producer
  namespace: app-spring
spec:
  output:
    to:
      kind: ImageStreamTag
      name: spring-artemis-producer:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-17:1.12
        namespace: openshift
    type: Source
