apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-artemis-producer
  namespace: app-spring
  serviceAccountName: openshift-pipelines-operator  
  labels:
    app: spring-artemis-producer
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-artemis-producer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: spring-artemis-producer
    spec:
      containers:
      - name: spring-artemis-producer
        # Usando a imagem base do repositório interno do OpenShift
        image: image-registry.openshift-image-registry.svc:5000/app-spring/spring-artemis-producer:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"  # Exemplo de configuração de perfil
        # - name: ARTEMIS_BROKER_URL
          # valueFrom:
            # configMapKeyRef:
              # name: artemis-config
              # key: broker-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always
