apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: spring-artemis-pipeline
  namespace: app-spring
  serviceAccountName: pipeline
spec:
  tasks:
    - name: build-image
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/app-spring/spring-artemis-producer:latest
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
    - name: deploy-to-openshift
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc apply -f https://raw.githubusercontent.com/oliveira-shiai/spring-artemis-producer-v2/main/deployment.yaml
            oc rollout status deployment/spring-artemis-deployment
