apiVersion: v1
kind: Service
metadata:
  name: spring-artemis-producer-service
  labels:
    app: spring-artemis-producer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-artemis-producer
  type: ClusterIP
