---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-kustomize-repo
  namespace: app-spring
  annotations:
    tekton.dev/displayName: "Update Kustomize Image in Git Repository"
spec:
  params:
  - name: gitRepositoryUrl
    description: URL of the Git repository to update
    type: string
    default: https://github.com/oliveira-shiai/gitops-repo
  - name: gitRepositoryRevision
    description: Branch or Tag to push the update to
    type: string
    default: main
  - name: gitPath
    description: Path in the repository to work in
    type: string
    default: apps/app-spring
  - name: fileName
    description: Name of the file to be updated
    type: string
    default: ./kustomization.yaml
  - name: image
    description: The image to be written into the YAML
    type: string
    default: image-registry.openshift-image-registry.svc:5000/app-spring/app-spring
  - name: imageTag
    description: The image tag to be written into the YAML
    type: string
    default: latest
  - name: verbose
    description: Log the commands used during execution
    type: string
    default: "true"
  volumes:
  - name: repository
    emptyDir: {}
  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "/workspace"
    volumeMounts:
    - name: repository
      mountPath: /workspace/repository
    script: |
      #!/usr/bin/env sh

      set -eu -o pipefail

      if [[ "$(params.verbose)" == "true" ]] ; then
        set -x
        echo "**** Cloning $(params.gitRepositoryUrl) into $(pwd)/repository"
      fi

      rm -rf $(pwd)/repo
      git clone "$(params.gitRepositoryUrl)" $(pwd)/repository
      cd repository
      git checkout "$(params.gitRepositoryRevision)"

  - name: update-yaml
    image: alpine/git:v2.26.2
    workingDir: "/workspace/repository"
    volumeMounts:
    - name: repository
      mountPath: /workspace/repository
    script: |
      #!/usr/bin/env sh
      set -e

      if [[ "$(params.verbose)" == "true" ]] ; then
        echo "**** Updating $(params.fileName) image to $(params.image):$(params.imageTag)"
      fi

      sed -r "s/^(\s*image\s*:\s*).*/\1$(params.image):$(params.imageTag)/" -i ./$(params.gitPath)/$(params.fileName)

  - name: commit-push-changes
    image: alpine/git:v2.26.2
    workingDir: "/workspace/repository"
    volumeMounts:
    - name: repository
      mountPath: /workspace/repository
    script: |
      #!/usr/bin/env sh
      set -e

      git config --global user.email "tekton@tekton.dev"
      git config --global user.name "OpenShift Pipelines"
      git add .
      git commit --allow-empty -m "Update $(params.image):$(params.imageTag)"
      git push origin "$(params.gitRepositoryRevision)"
