apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-spring-artemis-producer
  namespace: app-spring
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: admin
        generateName: spring-artemis-producer-
        labels:
          app.kubernetes.io/instance: spring-artemis-producer
          app.kubernetes.io/name: spring-artemis-producer
          operator.tekton.dev/operand-name: openshift-pipelines-addons
          pipeline.openshift.io/runtime: java
          pipeline.openshift.io/runtime-version: openjdk-17-ubi8
          pipeline.openshift.io/type: kubernetes
          tekton.dev/pipeline: spring-artemis-producer
        namespace: app-spring
      spec:
        params:
          - name: APP_NAME
            value: spring-artemis-producer
          - name: GIT_REPO
            value: 'https://github.com/oliveira-shiai/spring-artemis-producer-v2.git'
          - name: GIT_REVISION
            value: ''
          - name: IMAGE_NAME
            value: 'image-registry.openshift-image-registry.svc:5000/app-spring/spring-artemis-producer-v-2-git'
          - name: PATH_CONTEXT
            value: .
          - name: VERSION
            value: openjdk-17-ubi8
        pipelineRef:
          name: spring-artemis-producer


---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-producer
  namespace: app-spring  
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-spring-artemis-producer
